# Generated by Django 5.1.6 on 2025-03-04 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('organizations', '0002_alter_organization_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='authentication.authuser')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_employees', to='authentication.authuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_employee_relations', to='organizations.organization')),
            ],
            options={
                'db_table': 'manager_employee',
                'unique_together': {('manager', 'employee')},
            },
        ),
    ]
