# Generated by Django 5.1.6 on 2025-03-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver', models.IntegerField()),
                ('receiver', models.IntegerField()),
                ('organization_id', models.IntegerField()),
                ('feedback_type', models.CharField(max_length=50)),
                ('questions', models.JSONField()),
                ('answers', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
