# Generated by Django 5.1.6 on 2025-03-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_giver_alter_feedback_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Peer', 'Peer'), ('Self', 'Self')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='giver',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='organization_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='receiver',
            field=models.CharField(max_length=100),
        ),
    ]
