# Generated by Django 5.1.6 on 2025-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_swotanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='swotanalysis',
            name='performance_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
