version: "3.8"

services:
  db:
    image: postgres:15
    container_name: custom_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: custom_backend:latest
    container_name: custom_backend_container
    environment:
      DEBUG: "1"
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_NAME: mydatabase
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8001:8001"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: custom_frontend:latest
    container_name: custom_frontend_container
    ports:
      - "5173:5173"

volumes:
  postgres_data: