# Generated by Django 5.1.6 on 2025-03-04 05:24

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '__latest__'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey('authentication.AuthUser', on_delete=django.db.models.deletion.CASCADE, related_name='created_organizations', to_field='id'),
        ),
    ]
