# Generated by Django 5.1.6 on 2025-03-04 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('organizations', '0002_alter_organization_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_organizations', to='authentication.authuser'),
        ),
    ]
